name: nix flake check

permissions:
  contents: read
  statuses: write
  checks: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: bash status.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
